### PR TITLE
UPDATE Packages and Fix failing tests

### PR DESCRIPTION
**Pull request by alistairyves**
I updated the packages that were up to date, and changed an indent in the test which was causing the travis build to fail

tested on travis with my forked repo, and all tests pass with the updated packages

### CODE REVIEW

**Comment by alistairyves** [comment]
@remixz

**Comment by AnEmortalKid** [comment]
@alistairyves we might have to start our own fork. Mayhaps we could rebrand under dogelang

**Comment by Griffork** [comment]
If you do make sure you put a link here so that we can follow along!

**Comment by AnEmortalKid** [comment]
maybe @remixz or @Bartvds  can make alistair an owner of this, it looks like alex dantas has been mia on github for about 3 years :(

**Comment by alistairyves** [comment]
@anemortalkid well you can work on my fork if there is something you would like to ad. I just want dogescript to be up to date for non for the mean time

**Comment by alistairyves** [comment]
Npm

**Comment by AnEmortalKid** [comment]
Awesome. I did just add anonymous functions to my fork so I'll make sure to
PR that and figure it how to run the tests

**Comment by alistairyves** [comment]
Cool, I can take a look at it in the morning. You should be able to run Travis on your fork to see the tests run. Let me know if you have any questions

**Comment by AnEmortalKid** [comment]
I'll give it a shot tomorrow if I have time :) thanks a lot.

**Pull request merged**
