### PR TITLE
Thx with args

### PR DESCRIPTION
**Pull request by AnEmortalKid**
Part of #194 , this time handling the case with arguments

### CODE REVIEW

**Comment by vpzomtrrfrt** [comment]
Nested function calls would be worth adding tests for too

**Comment by AnEmortalKid** [comment]
> Nested function calls would be worth adding tests for too

Umm, mind sharing an example? If it’s with the `much` keyword I think I have an idea. Or are you thinking of the chained ones like `bar().baz()`

**Comment by vpzomtrrfrt** [comment]
> > Nested function calls would be worth adding tests for too
> 
> Umm, mind sharing an example? If it’s with the `much` keyword I think I have an idea. Or are you thinking of the chained ones like `bar().baz()`

I was thinking more like `plz a with b plz c with d e thx f thx`

**Comment by AnEmortalKid** [comment]
Ah, `plz a with b plz c with d e thx f thx`

To produce `a(b, c(d,e))`.

I don’t think I’ve handled that yet, but I’ll see if the handling of arguments is enough!

**Comment by AnEmortalKid** [comment]
Welll, that's gonna need some work

```
$ dogescript testlet.djs
a(b, plz, c, with, d, e)f thx

$ cat testlet.djs
plz a with b plz c with d e thx f thx
```

Mostly cause of the way the arguments are handled: https://github.com/dogescript/dogescript/pull/199/files#diff-3fab227e34d65fe9bb2d6ea53eec41cfR712

I've done some exploration of trying to tackle the ambiguity of keywords here #200 by making a stack of states (of kinds). I'll create an issue to follow up on seeing what it's gonna take to make that case work

@vpzomtrrfrt ^

**Comment by AnEmortalKid** [comment]
Logged #201 to address testing gaps.

**Pull request merged**
