### PR TITLE
fix inlined json

### LINKED ISSUE #187: Object declaration with curly braces no longer works
To be fair, a lot of the doge3 source is workarounds for the way 2.3 handles things, but ideally we wouldn't be breaking anything in 2.4.

This snippet (line 267):
```
result is {
    'type': 'call',
    'function': callee,
    'args': args
}
```
Formerly compiled this way:
```
result = {
                        'type': 'call',
                        'function': callee,
                        'args': args
                }
```
But now results in this:
```
result = {
;
'type' : 'call' ,
'function' : callee,
'args' : args
}
```
There's an extra semicolon after the opening brace now, which throws a SyntaxError when run

### PR DESCRIPTION
**Pull request by AnEmortalKid**
Fixes #187 

thx for finding this @vpzomtrrfrt . 

The spacing also doesn't get ruined.

### CODE REVIEW

**Comment by vpzomtrrfrt** [comment]
Seems like it's missing a semicolon at the end still.  Not that it's there in 2.3, but it might be worth fixing while we're here

**Comment by AnEmortalKid** [comment]
I’ll see why it’s not adding that, iirc it should but maybe shouldCloseStatement is too restrictive.

**Comment by AnEmortalKid** [comment]
Ah, it looks like it falls into the `isDogescriptSource` chunk after the first line:

```
result = {
```

We handle correctly through assignOps. 

```
 'type': 'call',
 'function': callee,
  'args': args
}
```

All return as is since they fall through as not being dogescript. This one might be tricky to fix as part of this. We might have to keep track of some state:

`{` -> JSON_OPEN
`}` -> JSON_CLOSE

Once we see JSON_CLOSE, we can append a `;`. 

I'll play around with some ideas in the next couple of days and if it proves a bit more challenging i'll create a new issue.

**Comment by AnEmortalKid** [comment]
Well, i came up with something that's ending up adding ; to everything........ I might log an issue for this just to think more on it. https://github.com/AnEmortalKid/dogescript/blob/fix-187-options/lib/parser.js#L4

https://travis-ci.org/AnEmortalKid/dogescript/builds/493569995

I think the state i probably need to track in this instance if it's in an assignment (just to add ';') to all assignment operations. 

I'll probably also log an issue for the 3.0.0 features to re-write the REPL. I think part of the tough part here is that the current line might not be the finite input: http://dogescript.io/news/progress-update-2

**Comment by AnEmortalKid** [comment]
Created #190  to avoid holding up this pr. @vpzomtrrfrt any other concerns?

**Pull request merged**
